name: CI Pipeline
on: workflow_dispatch
jobs:
  RunMake:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Run Make
        run: make  # Запускаем команду make

  RunTest:
    needs: RunMake  # Запускать после завершения RunMake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: make test  # Запускаем тесты (предполагается, что у вас есть цель test в Makefile)

  RunPackage:
    needs: RunTest  # Запускать после завершения RunTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Package
        run: make package  # Запускаем упаковку (предполагается, что у вас есть цель package в Makefile)
