name: CI Pipeline
on: workflow_dispatch
jobs:
  RunMake:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Run Make
        working-directory: ./src
        run: make 

  RunTest:
    needs: RunMake 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        working-directory: ./src
        run: make test  

  RunPackage:
    needs: RunTest 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Package
        working-directory: ./src
        run: make package  
